/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:47f87349-47e5-46c9-b1a0-ddb8f3229cb1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9WHXRVmbW",
    "aws_user_pools_web_client_id": "1d2a0152au7lkf2ag1aphg43fo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gcabxybrufa7rnyqsg5vfdlqu4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kfbvltxwi5dllhgkjcgnzpjyky"
};


export default awsmobile;
